services:
  mongodb:
    image: mongo:latest
    container_name: local_mongodb
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./backend/db/mongodb/data:/data/db
      - ./backend/db/mongodb/schema/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  weaviate:
    image: semitechnologies/weaviate:1.34.1
    container_name: local_weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: always
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 5
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      AUTHENTICATION_APIKEY_ENABLED: "false"
      AUTHENTICATION_APIKEY_USERS: ${WEAVIATE_APIKEY_USER}
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_APIKEY_KEY}
      CORS_ALLOW_ORIGIN: "http://localhost:3000"
      CORS_ALLOW_HEADERS: "Content-Type,Authorization,X-API-KEY"
      CORS_ALLOW_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node_local"
    volumes:
      - ./backend/db/weaviate/data:/var/lib/weaviate
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8080/v1/.well-known/ready >/dev/null 2>&1 || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  weaviate-console:
    image: semitechnologies/weaviate-console:latest
    container_name: local_weaviate_console
    ports:
      - "3000:80"
    environment:
      - WEAVIATE_URL=http://localhost:8080
    depends_on:
      weaviate:
        condition: service_healthy

  # verba:
  #   image: semitechnologies/verba:latest
  #   container_name: local_verba
  #   ports:
  #     - "8008:8000"
  #   environment:
  #     - WEAVIATE_URL_VERBA=http://weaviate:8080
  #     - WEAVIATE_API_KEY_VERBA=${WEAVIATE_APIKEY_KEY}
  #   depends_on:
  #     weaviate:
  #       condition: service_healthy
  #   restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    container_name: wikipedia_scraper
    volumes:
      - ./data/wiki_dumps:/app/data/wiki_dumps
    env_file:
      - .env
    profiles: ["tools"]